name: daily-study-agent

on:
  schedule:
    - cron: '0 3 * * *'   # once daily at 03:00 UTC; change as needed
  workflow_dispatch: {}

permissions:
  contents: write  # needed to push changes

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run agent
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
          HF_MODEL: 'google/flan-t5-base'   # override model if you want
          EXAM_DATE: ${{ vars.EXAM_DATE }}   # OR set EXAM_DATE below in env
          DAILY_HOURS: ${{ vars.DAILY_HOURS }}
        run: |
          python agentic_study_agent.py

      - name: Commit plan.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plan.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update plan.json (agent)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
